In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
## from sklearn import svm

## Process data for use in Machine learning
### We import data of the English Premier League 2017/2018 season

In [3]:
ep1718s=pd.read_csv("data/E0_1718.csv")
ep1718s.columns

Index(['Div', 'Date', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HTHG',
       'HTAG', 'HTR', 'Referee', 'HS', 'AS', 'HST', 'AST', 'HF', 'AF', 'HC',
       'AC', 'HY', 'AY', 'HR', 'AR', 'B365H', 'B365D', 'B365A', 'BWH', 'BWD',
       'BWA', 'IWH', 'IWD', 'IWA', 'LBH', 'LBD', 'LBA', 'PSH', 'PSD', 'PSA',
       'WHH', 'WHD', 'WHA', 'VCH', 'VCD', 'VCA', 'Bb1X2', 'BbMxH', 'BbAvH',
       'BbMxD', 'BbAvD', 'BbMxA', 'BbAvA', 'BbOU', 'BbMx>2.5', 'BbAv>2.5',
       'BbMx<2.5', 'BbAv<2.5', 'BbAH', 'BbAHh', 'BbMxAHH', 'BbAvAHH',
       'BbMxAHA', 'BbAvAHA', 'PSCH', 'PSCD', 'PSCA'],
      dtype='object')

* We take the odds provided by the bet365 entity and try to use them to predict outcomes

In [4]:
features=['HomeTeam','AwayTeam','B365H','B365D','B365A','FTR']
new_df=ep1718s[features]
new_df.shape

(380, 6)

In [5]:
new_df.head()

HomeTeam      AwayTeam  B365H  B365D  B365A FTR
0         Arsenal     Leicester   1.53    4.5   6.50   H
1        Brighton      Man City  11.00    5.5   1.33   A
2         Chelsea       Burnley   1.25    6.5  15.00   A
3  Crystal Palace  Huddersfield   1.83    3.6   5.00   A
4         Everton         Stoke   1.70    3.8   5.75   H

In [6]:
## Assuming the Odds determine the outcome and none other.
Outcomes=[]
for i in range(len(new_df['FTR'])):
    if new_df['FTR'][i] is 'H':
        Outcomes.append(1)
    elif new_df['FTR'][i] is 'D':
        Outcomes.append(2)
    else:
        Outcomes.append(3)
len(Outcomes)

380

In [7]:
ready_df=new_df[['B365H','B365D','B365A']]
ready_df["Result"]=Outcomes
ready_df.head()

/home/african/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  


B365H  B365D  B365A  Result
0   1.53    4.5   6.50       1
1  11.00    5.5   1.33       3
2   1.25    6.5  15.00       3
3   1.83    3.6   5.00       3
4   1.70    3.8   5.75       1

In [8]:
ready_df.to_csv("E0_1718_numerical.csv",index=False
               )

In [1]:
from sklearn import svm

In [9]:
np.unique(ready_df.Result)

array([1, 2, 3])

# Training Classifiers on the 2017/18 Premier league dataset. 
We start with the simplest classifier, the KNearestNeighbours
## KNN (K nearest neighbours)

In [13]:
X=ready_df[['B365H','B365D','B365A']]
y=ready_df[['Result']]

In [14]:
X_train=X[:-30]
y_train=y[:-30]
X_test=X[-30:]
y_test=y[-30:]
print("Training Data: ",X_train.shape,y_train.shape)
print("Testing Data: ",X_test.shape,y_test.shape)

Training Data:  (350, 3) (350, 1)
Testing Data:  (30, 3) (30, 1)


In [16]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier()
knn.fit(X_train,y_train)

/home/african/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [17]:
knn.predict(X_test)

array([3, 1, 3, 1, 2, 1, 1, 1, 2, 1, 3, 1, 1, 1, 2, 1, 3, 1, 1, 3, 1, 3,
       3, 1, 1, 3, 3, 1, 1, 1])

In [21]:
np.array(y_test).T.flatten()

array([3, 1, 3, 1, 1, 1, 2, 3, 3, 1, 1, 1, 1, 2, 3, 2, 1, 1, 1, 2, 3, 1,
       3, 1, 1, 1, 3, 3, 1, 1])

In [22]:
knn.predict(X_test)-np.array(y_test).T.flatten()

array([ 0,  0,  0,  0,  1,  0, -1, -2, -1,  0,  2,  0,  0, -1, -1, -1,  2,
        0,  0,  1, -2,  2,  0,  0,  0,  2,  0, -2,  0,  0])

## SVC Support Vector Classifier
Let's try another classifier and see how it goes



In [31]:
from sklearn import svm
svc=svm.SVC(kernel='linear')
svc.fit(X_train,y_train)

/home/african/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [32]:
svc.predict(X_test)

array([3, 1, 3, 1, 3, 1, 1, 1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1, 1,
       3, 1, 1, 3, 3, 1, 1, 1])

In [33]:
np.array(y_test).T.flatten()

array([3, 1, 3, 1, 1, 1, 2, 3, 3, 1, 1, 1, 1, 2, 3, 2, 1, 1, 1, 2, 3, 1,
       3, 1, 1, 1, 3, 3, 1, 1])

In [34]:
svc.predict(X_test)-np.array(y_test).T.flatten()

array([ 0,  0,  0,  0,  2,  0, -1, -2, -2,  0,  2,  0,  0, -1, -2, -1,  0,
        0,  0,  1, -2,  0,  0,  0,  0,  2,  0, -2,  0,  0])

In [41]:
svc1=svm.SVC(kernel='rbf')
svc1.fit(X_train,y_train)

/home/african/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/african/anaconda3/lib/python3.6/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [42]:
svc1.predict(X_test)

array([3, 1, 3, 1, 3, 1, 2, 1, 1, 1, 3, 1, 1, 1, 2, 1, 3, 1, 1, 3, 1, 1,
       3, 1, 1, 3, 3, 1, 1, 1])

In [43]:
svc1.predict(X_test)-np.array(y_test).T.flatten()

array([ 0,  0,  0,  0,  2,  0,  0, -2, -2,  0,  2,  0,  0, -1, -1, -1,  2,
        0,  0,  1, -2,  0,  0,  0,  0,  2,  0, -2,  0,  0])

In [46]:
svc2=svm.SVC(kernel='poly',degree=2,gamma='auto')
svc2.fit(X_train,y_train)
print(svc2.predict(X_test))
print(svc2.predict(X_test)-np.array(y_test).T.flatten())

/home/african/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[3 1 3 1 2 1 1 1 1 1 3 1 1 1 1 1 2 1 1 3 1 1 3 1 1 3 3 1 1 1]
[ 0  0  0  0  1  0 -1 -2 -2  0  2  0  0 -1 -2 -1  1  0  0  1 -2  0  0  0
  0  2  0 -2  0  0]


### Let's check the scores for our classifiers to determine a good one.
For the knn, svc, svc1,svc2

In [47]:
print("KNN scores: ",knn.score(X_test,y_test))
print("SVC scores with linear kernel: ",svc.score(X_test,y_test))
print("SVC1 scores with rbf kernel: ",svc1.score(X_test,y_test))
print("SVC2 scores with poly kernel degree 2: ",svc2.score(X_test,y_test))

KNN scores:  0.5333333333333333
SVC scores with linear kernel:  0.5666666666666667
SVC1 scores with rbf kernel:  0.6
SVC2 scores with poly kernel degree 2:  0.5666666666666667


In [50]:
from sklearn.model_selection import KFold,cross_val_score
k_fold=KFold(n_splits=7)
print(cross_val_score(svc1,X,y,cv=k_fold,n_jobs=-1),'\n\n')
print(cross_val_score(svc1,X,y,cv=k_fold,n_jobs=-1,scoring='precision_macro'))

[0.58181818 0.58181818 0.57407407 0.51851852 0.48148148 0.53703704
 0.5       ] 


[0.59242424 0.73150106 0.4025974  0.37261905 0.38403263 0.49446589
 0.41351351]


In [57]:
from sklearn.model_selection import GridSearchCV
Cs=np.logspace(-1,6,13)
clf=GridSearchCV(estimator=svc1,param_grid=dict(C=Cs),n_jobs=-1)
clf.fit(X_train,y_train)


/home/african/anaconda3/lib/python3.6/site-packages/sklearn/model_selection/_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
/home/african/anaconda3/lib/python3.6/site-packages/sklearn/model_selection/_search.py:813: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)
/home/african/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/african/anaconda3/lib/python3.6/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale'

GridSearchCV(cv='warn', error_score='raise-deprecating',
             estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='auto_deprecated', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='warn', n_jobs=-1,
             param_grid={'C': array([1.00000000e-01, 3.83118685e-01, 1.46779927e+00, 5.62341325e+00,
       2.15443469e+01, 8.25404185e+01, 3.16227766e+02, 1.21152766e+03,
       4.64158883e+03, 1.77827941e+04, 6.81292069e+04, 2.61015722e+05,
       1.00000000e+06])},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [58]:
clf.best_score_

0.5257142857142857

In [59]:
clf.best_estimator_.C

1.4677992676220697

In [61]:
clf.score(X_train,y_train)

0.5542857142857143

In [62]:
clf.score(X_test,y_test)

0.6

In [63]:
clf.score(X,y)

0.5578947368421052